server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /**
  packages-to-scan: com.pluralsight.conference.demo
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
    hibernate.use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    baseline-on-migrate: true

app.version: 1.0.0