version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=conference_demo
      - POSTGRES_USER=conference_user
      - POSTGRES_PASSWORD=conference_pass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local